### ISSUE TITLE
ECT I COP 18 FAST Tool Analysis

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/HSS-KP#15]
Use COP 18 FAST tool to calculate SD, Site NSD, and Above Site budget allocations for 8 OUs:

- [x] Burundi
- [x] Eswatini
- [x] Ethiopia
- [x] Kenya
- [x] Namibia
- [x] Rwanda
- [x] Zimbabwe

Using the following approach:
Source data:  FAST SO Entry Tab
**Step 1:  Created an HTS program area**
 If SO was listed as C&T and had any new $ in HVCT, I made the assumption that it was a "testing" activity.  This is not a perfect assumption (see my notes in file), but could be an ok proxy.  
**Step 2:  Determined SD, NSD, ASP Categorization** 
Calculated based on "approach" column based on definitions in COP guidance; see formulas in Column K on SO Level Determination tab 
**Step 3:  Ran analytics/summaries**
Summed SD/Site NSD/ASP by program area.  You'll see some weird stuff - e.g. systems level budget at site level, but this could either be hand adjusted or just taken as an artifact of the way FAST was set up and/or my methodology

**Comment by Yabayabadoo** [comment]
Adding Cambodia, but OU does not have a COP 18 FAST tool

- [ ] Cambodia

**Comment by Yabayabadoo** [comment]
@wvp3 @kkale25 The task is to create an SO Level Determination Tab for all OUs listed above. I will post all the FAST tools on pepfar.net and share the link in an hour. 

@wvp3 OUs: 

- [ ] Cambodia (perhaps you have access to an in country FAST?), 
- [ ] Kenya, 
- [ ] Eswatini


@kkale25 OUs: Burundi, Ethiopia, Zimbabwe

- [ ] Burundi, 
- [ ] Ethiopia, 
- [ ] Zimbabwe

**Comment by Yabayabadoo** [comment]
FAST Tools located [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHSS%2FProjects%2FECT%20I%20ER%20and%20FAST%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

**Comment by Yabayabadoo** [comment]
Analysis completed by @kkale25 and @Yabayabadoo

**Comment by jb3436** [comment]
This issue was moved to ICPI/Engagements#47
