### ISSUE TITLE
Key populations dashboard PSNU feasibility study 

### ISSUE THREAD

**Issue by wvp3** [ICPI/HSS-KP#17]
Explore feasibility of adding PSNU (or SNU1) level disaggregation to the KP dashboard.  This will add a geographic component to our tool, similar to many other ICPI tools.  

Due to privacy concerns, certain countries with small geographic area PSNUs will be shown at the SNU1 level.

**Comment by wvp3** [comment]
Completed several meetings/calls with the GIS workstream to discuss mapping of KP MER indicators.  PAWS visual crossings have been identified as a platform for a pilot map.  The proposal is to select two countries to create example maps (limited to PAWS only, not Panorama widely)

**Comment by vanamala-narasimhan** [comment]
Creation of 2 visual crossing maps for review by GIS team - meeting to be set up post COP 19

**Comment by vanamala-narasimhan** [comment]
Closed due to KP analyses being pushed for in dossiers
