### ISSUE TITLE
ICPI KP TOOL enhancement

### ISSUE THREAD

**Issue by jaliasd** [ICPI/HSS-KP#18]
Team: Please drop (dplyr:select) extraneous columns in the KP tool. This will make it smaller and improve usability. We should do this for all ICPI tools

For example.

ageasentered | agefine | agesemifine | agecoarse | sex | resultstatus | otherdisaggregate | coarsedisaggregate | modality | ismcad

**Comment by jb3436** [comment]
@jaliasd good comment. Feel free to send out a communication with the guidance to the tool POCs or send the more fleshed out text to @hessionra to send from ICPI.

**Comment by vanamala-narasimhan** [comment]
Code updated with fewer, essential columns for Key Pops OUxIM tool
