### ISSUE TITLE
Add HTS yield comparisons to KP dashboard

### ISSUE THREAD

**Issue by wvp3** [ICPI/HSS-KP#20]

**Comment by wvp3** [comment]
Ryan - by any chance do you have code or other methodology used to create the dataset for the modality vs. KP yield comparisons?

Thanks.

Travis

**Comment by oyd6** [comment]
Hey Travis,
Yes, I have the R code for the pull and I’ll upload it shortly. FYI: in the version sent to the ECT, I created the “KP Mechanism” variable in Excel; after I sent it out, I tweaked the R code to reproduce the same so the value names will be a bit different.

Ryan Keating
Epidemiologist
HIV Prevention Branch
Division of Global HIV & TB
oyd6@cdc.gov | 404-718-7481 office | 404-406-0848 mobile
*Sent from iPhone, please excuse any spelling or grammatical errors.
________________________________

**Comment by oyd6** [comment]
R code for data pull uploaded under COP19 folder. Excel pivot tables should be straight forward enough; positivity variable added as Calculated Field in Excel.

**Comment by wvp3** [comment]
Done.
