### ISSUE TITLE
Tanzania HRH analysis

### ISSUE THREAD

**Issue by wvp3** [ICPI/HSS-KP#4]
Visualize relationship between PEPFAR support of HRH salaries and treatment program results.  Ad-hoc request, requestor: S/GAC.

**Comment by wvp3** [comment]
Tanzania has shared an FY2018 version of their HRH inventory dataset.  An updated analysis will be repeated with this dataset, with the product being used during COP19 planning and review.  

Yaa will work on this initially as the primary analyst.

**Comment by Yabayabadoo** [comment]
Initial Analysis completed and shared with team on 2/13/2019. Next steps

- [ ] Merge FY17 MER Data

- [ ] Determine Feasibility of Merging FY16 HRH inventory dataset

- [ ] Conduct comparative analysis of HRH staff count and performance on clinical cascade

**Comment by wvp3** [comment]
There are major concerns about the Facility names in the HRH dataset.  The facility names in the HRH inventory do not match well with the MER facility names from DATIM.  I would say only about 10% of the facility names had exact matches, approximately.

In order to make the Tz Inventory data easily useable for analysis, whoever entered the data had to have used PEPFAR names as officially assigned in DATIM, or used the PEPFAR unique identification number (UID) for that Facility as assigned in DATIM.  PEPFAR implementing partners should know all of their correct site names based on when they enter their data into DATIM for MER reporting.

**Comment by wvp3** [comment]
The R stringdist package has been used as a way to parse text strings with the facility names from the two datasets (HRH inventory and DATIM/MER).  A penalized Jaro-Winkler algorithm was applied.  The number of matches found using this algorithm increased to about 650 sites in the HRH inventory out of the total ~2671 sites that reported on TX_CURR in DATIM.  However, some of those matches may not be correct.  We are waiting on the TZ to either further correct the facility names or confirm to proceed with analysis of some or all of the 650 sites.

**Comment by wvp3** [comment]
Update: the team sent back an updated HRH inventory file with many site names better rationalized with PEPFAR DATIM site names.  We performed the merge and created provisional visualizations, sharing the initial results with the team.  Pending QC and full review, we will finalize and share code and outputs.

**Comment by wvp3** [comment]
Update: this analysis was completed and reviewed for data correctness.  It was submitted back to the team.  However one Tanzania team member reported some difficulty viewing the html figures on a laptop.  Others from various agencies could see the figures on various devices.
As of 4/22, a sub-analysis was also performed on a subset of 231 high-priority sites in preparation for the reboot reverse TDY COP meetings.
