### ISSUE TITLE
DRT / quality checks for HRH_CURR indicator

### ISSUE THREAD

**Issue by wvp3** [ICPI/HSS-KP#8]
Create a list of checks or rules that could be applied to HRH_CURR indicator at the site, SNU or national level to objectively determine the quality and completeness of the data.

**Comment by jb3436** [comment]
Bringing this back up since Leigh and Shazad are requesting additional checks for the DRT.

**Comment by wvp3** [comment]
Preliminary proposed validation checks based on discussion with technical area experts in HRH

1)	Flag if HRH_CURR >= HRH_STAFF.  Normal if HRH_CURR < HRH_STAFF.  Flag at the site level and PSNU level.  Flag message: “HRH_CURR (PEPFAR-supported HRH) should be a subset of HRH_STAFF (total HRH present).”
2)	Flag if HRH_CURR > 0 and sum of all DSD-type indicators = 0.  Flag at the site level and PSNU level.  Flag message: “Sites with PEPFAR HRH support should be reporting program results in the ‘DSD’ category.”
3)	Flag if HRH_CURR > 0 and site type is NOT scale-up (at the site level).  Flag message: “Do not expect PEPFAR support of HRH in non-scale-up sites.” [Note: need to standardize definition of scale-up vs.  non-scaleup over fiscal years]
4)	Flag if the rolled up HRH_CURR (CadreCategory/Financial Support) > 0 and PSNU type is NOT scale-up (at the PSNU level)
Do not count HRH_CURR (CadreOU/Financial Support) in this flag.  Flag message: “Do not expect PEPFAR support of HRH in non-scale-up districts.” [Note: need to standardize definition of scale-up vs.  non-scaleup over fiscal years]

**Comment by wvp3** [comment]
Update on 4/1/2019: S/GAC has stated that there will be DRT checks for HRH_CURR scheduled for FY2019Q4 release.
